print(f'Please fill in the blanks')
print(f'__(name)__\'s favorite subject in school is __(subject)__')
name=input(f'What is the name? ')
subject=input("Which subject? ")
print(f'{name}\'s favorite subject in school is {subject}')